const STORAGE_KEY = 'coral-jubilo-relatorios-v1'
const TOKEN_KEY = 'coral-jubilo-github-token'
const GITHUB_FILE = 'dados/relatorios.csv'
const GITHUB_API = 'https://api.github.com/repos/marcelofaria/coral-jubilo-celeste/contents/'
const today = () => new Date().toISOString().slice(0, 10)
const $ = selector => document.querySelector(selector)
const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#039;', '"':'&quot;' }[character]))
const csvValue = value => `"${String(value || '').replace(/"/g, '""')}"`
const parseCsvLine = line => line.match(/(?:^|;)("(?:[^"]|"")*"|[^;]*)/g).map(value => value.replace(/^;/, '').replace(/^"|"$/g, '').replace(/""/g, '"'))
const blankReport = () => ({ id: crypto.randomUUID(), data: today(), atividade: 'Ensaio', hinos: '', regencia: '', musicos: '', oferta: '', observacoes: '' })
let state = { reports: [], editingId: null }
try { state.reports = JSON.parse(localStorage.getItem(STORAGE_KEY))?.reports || [] } catch { state.reports = [] }
state.reports = state.reports.map(report => ({ ...report, hinos: report.hinos || report.hinos_ensaio || report.hinos_culto || '' }))
let githubToken = localStorage.getItem(TOKEN_KEY)
function saveLocal(message) { localStorage.setItem(STORAGE_KEY, JSON.stringify({ reports: state.reports })); $('#save-status').textContent = message || 'alterações salvas neste dispositivo' }
function buildCsv() { const headers = ['tipo','data','atividade','hinos','regencia','musicos','oferta','observacoes']; return [headers, ...state.reports.sort((a,b) => a.data.localeCompare(b.data)).map(report => headers.map(header => header === 'tipo' ? 'relatorio' : report[header] || ''))].map(row => row.map(csvValue).join(';')).join('\r\n') + '\r\n' }
function formatDate(date) { return new Intl.DateTimeFormat('pt-BR', { day:'2-digit', month:'short', year:'numeric' }).format(new Date(`${date}T12:00:00`)) }
function renderFilters() { const selectedYear = $('#year-filter').value || 'all'; const years = [...new Set(state.reports.map(report => report.data.slice(0,4)))].sort().reverse(); $('#year-filter').innerHTML = '<option value="all">todos os anos</option>' + years.map(year => `<option>${year}</option>`).join(''); $('#year-filter').value = years.includes(selectedYear) ? selectedYear : 'all' }
function render() { renderFilters(); const year = $('#year-filter').value; const activity = $('#activity-filter').value; const reports = state.reports.filter(report => (year === 'all' || report.data.startsWith(year)) && (activity === 'all' || report.atividade === activity)).sort((a,b) => b.data.localeCompare(a.data)); $('#report-list').innerHTML = reports.map(report => { const hymns = report.hinos || ''; return `<article class="report-card"><div class="report-date"><strong>${formatDate(report.data)}</strong><span>${report.data.slice(0,4)}</span></div><div class="report-activity activity-${report.atividade.toLowerCase()}"><strong>${escapeHtml(report.atividade)}</strong><span>${report.oferta ? `R$ ${escapeHtml(report.oferta)}` : 'sem oferta'}</span></div><div class="report-content"><h3>${escapeHtml(hymns || 'Registro sem hinos informados')}</h3>${report.regencia ? `<p><b>Regência:</b> ${escapeHtml(report.regencia)}</p>` : ''}${report.musicos ? `<p><b>Músicos:</b> ${escapeHtml(report.musicos)}</p>` : ''}${report.observacoes && report.observacoes !== hymns ? `<p><b>Notas:</b> ${escapeHtml(report.observacoes)}</p>` : ''}</div><div class="report-actions"><button class="icon-button" data-edit="${report.id}" aria-label="Editar relatório">✎</button><button class="icon-button delete" data-delete="${report.id}" aria-label="Excluir relatório">×</button></div></article>` }).join(''); $('#empty-state').hidden = reports.length > 0 }
function fillForm(report) { state.editingId = report.id; $('#editor-title').textContent = 'Editar relatório'; $('#report-id').value = report.id; const fields = { 'report-date':'data', 'report-activity':'atividade', hymns:'hinos', conductors:'regencia', musicians:'musicos', offer:'oferta', notes:'observacoes' }; Object.entries(fields).forEach(([id, key]) => { $(`#${id}`).value = report[key] || '' }); $('#editor-section').scrollIntoView({ behavior:'smooth', block:'start' }) }
function clearForm() { state.editingId = null; $('#editor-title').textContent = 'Novo relatório'; $('#report-form').reset(); $('#report-date').value = today() }
function csvToReports(text) { const headers = parseCsvLine(text.split(/\r?\n/, 1)[0]); return text.trim().split(/\r?\n/).slice(1).filter(Boolean).map(line => { const values = parseCsvLine(line); const record = Object.fromEntries(headers.map((header, index) => [header, values[index] || ''])); return { id: crypto.randomUUID(), data: record.data || today(), atividade: record.atividade || 'Ensaio', hinos: record.hinos || record.hinos_ensaio || record.hinos_culto || '', regencia: record.regencia || '', musicos: record.musicos || '', oferta: record.oferta || '', observacoes: record.observacoes || '' } }) }
async function loadRepositoryCsv() { if (state.reports.length) return; try { const response = await fetch('../dados/relatorios.csv', { cache:'no-store' }); if (response.ok) { state.reports = csvToReports(await response.text()); saveLocal('histórico carregado do repositório'); render() } } catch (error) { console.warn('CSV de relatórios indisponível', error) } }
function encodeBase64(value) { const bytes = new TextEncoder().encode(value); let binary = ''; bytes.forEach(byte => { binary += String.fromCharCode(byte) }); return btoa(binary) }
async function saveToGithub() { if (!githubToken) { configureGithub(); if (!githubToken) return } const headers = { Accept:'application/vnd.github+json', Authorization:`Bearer ${githubToken}`, 'X-GitHub-Api-Version':'2022-11-28' }; $('#save-status').textContent = 'enviando commit para o GitHub...'; try { const url = `${GITHUB_API}${GITHUB_FILE}`; const current = await fetch(`${url}?ref=main`, { headers }); if (![200,404].includes(current.status)) throw new Error(`não foi possível localizar o CSV (${current.status})`); const file = current.status === 200 ? await current.json() : {}; const payload = { message:`Atualiza relatórios do coral (${today()})`, content:encodeBase64(buildCsv()), branch:'main' }; if (file.sha) payload.sha = file.sha; const response = await fetch(url, { method:'PUT', headers:{...headers,'Content-Type':'application/json'}, body:JSON.stringify(payload) }); if (!response.ok) throw new Error((await response.json()).message || `GitHub respondeu ${response.status}`); $('#save-status').textContent = 'salvo no GitHub · commit criado' } catch (error) { $('#save-status').textContent = 'erro ao salvar no GitHub'; window.alert(`Falha ao salvar: ${error.message}`) } }
function configureGithub() { const token = window.prompt('Cole seu token fine-grained do GitHub com Contents: Read and write.'); if (token) { githubToken = token.trim(); localStorage.setItem(TOKEN_KEY, githubToken); $('#configure-github').textContent = 'remover configuração' } }
$('#report-form').addEventListener('submit', event => { event.preventDefault(); const values = { data:$('#report-date').value, atividade:$('#report-activity').value, hinos:$('#hymns').value.trim(), regencia:$('#conductors').value.trim(), musicos:$('#musicians').value.trim(), oferta:$('#offer').value, observacoes:$('#notes').value.trim() }; if (state.editingId) state.reports = state.reports.map(report => report.id === state.editingId ? { ...report, ...values } : report); else state.reports.push({ id:crypto.randomUUID(), ...values }); saveLocal('relatório salvo neste dispositivo'); clearForm(); render() })
$('#new-report').addEventListener('click', () => { clearForm(); $('#editor-section').scrollIntoView({ behavior:'smooth', block:'start' }) }); $('#clear-form').addEventListener('click', clearForm); $('#cancel-edit').addEventListener('click', clearForm); $('#year-filter').addEventListener('change', render); $('#activity-filter').addEventListener('change', render)
$('#report-list').addEventListener('click', event => { const edit = event.target.closest('[data-edit]'); const remove = event.target.closest('[data-delete]'); if (edit) fillForm(state.reports.find(report => report.id === edit.dataset.edit)); if (remove && window.confirm('Excluir este relatório?')) { state.reports = state.reports.filter(report => report.id !== remove.dataset.delete); saveLocal('relatório excluído'); render() } })
$('#save-reports').addEventListener('click', saveToGithub); $('#configure-github').addEventListener('click', () => { if (githubToken && window.confirm('Remover o token salvo deste navegador?')) { githubToken = null; localStorage.removeItem(TOKEN_KEY); $('#configure-github').textContent = 'configurar GitHub' } else if (!githubToken) configureGithub() }); $('#export-reports').addEventListener('click', () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([buildCsv()], { type:'text/csv;charset=utf-8' })); link.download = 'relatorios.csv'; link.click(); URL.revokeObjectURL(link.href) })
$('#report-date').value = today(); if (githubToken) $('#configure-github').textContent = 'remover configuração'; render(); loadRepositoryCsv()